language: generic

sudo: false

matrix:
  include:
    - os: osx
      env: TEST_TARGET=environment
    - os: osx
      env: TEST_TARGET=notebooks
    - os: linux
      env: TEST_TARGET=notebooks
    - os: linux
      env: TEST_TARGET=environment

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then URL="https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then URL="https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" ; fi
  # GUI (R png figures)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; sh -e /etc/init.d/xvfb start ; fi
  - wget $URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes --all
  # Env creation.
  - conda-env create -f environment.yml
  - source activate CBO2016
  # Fortran cells.
  - conda install gcc --yes

script:
  - if [[ $TEST_TARGET == 'environment' ]]; then
      jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=18000 notebooks/check_env.ipynb ;
    fi

  - if [[ $TEST_TARGET == 'notebooks' ]]; then
      jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=18000 notebooks/slides.ipynb ;
    fi
