os:
  - linux
  - osx

sudo: false

addons:
  artifacts: true

install:
    - URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then URL="http://bit.ly/miniconda" ; fi
    - wget $URL -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda install --yes constructor

script:
  - constructor distribution
