os:
  - osx
  - linux

sudo: false

install:
  - URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
  - wget $URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes --all
  - conda install --yes constructor

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then constructor --verbose --platform=osx-64 distribution ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then constructor --verbose --platform=linux-64 distribution ; fi
