language: generic

sudo: false

os:
  - osx
  - linux


install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" ; fi
  - wget $URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes --all
  - conda-env create -f environment.yml
  - source activate CBO2016

script:
  - jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=240 notebooks/check_env.ipynb
