build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"


install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda update --all --yes
  - "conda-env create -f environment.yml"
  - activate CBO2016
  - conda install console_shortcut --yes

test_script:
  - jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=240 notebooks/check_env.ipynb
