build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"


install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda update --all --yes
  - "conda-env create -f environment.yml"
  - activate CBO2016
  - conda install console_shortcut --yes
  # FIXME: Fortran cells.
  - conda install -c conda-forge mingwpy --yes
  - set CFG=%CONDA_PREFIX%\Lib\distutils\distutils.cfg
  - echo [build] >> "%CFG%"
  - echo compiler=mingw32 >> "%CFG%"

test_script:
  - jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 notebooks/check_env.ipynb
  - jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 notebooks/slides.ipynb
