name: CBO2016
channels:
  - ioos
  - defaults
  - r
  - conda-forge
dependencies:
  - python=2.7
  - pip
  - psutil
  - nb_conda_kernels
  - altair
  - anaconda-navigator
  - cartopy
  - clusterpy
  - cmocean
  - contextily
  - ctd
  - cython
  - dask
  - fiona
  - folium
  - fortran-magic
  - gdal
  - geopandas
  - gsw
  - hdf5
  - iris
  - jupyter
  - matplotlib
  - mplleaflet
  - netcdf4
  - numba
  - numpy
  - oceans
  - oct2py
  - pandas
  - pyproj
  - pyshp
  - qgrid
  - r-essentials
  - r-oce
  - rasterio
  - requests
  - rpy2
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - xarray
  - xlrd
  - xlsxwriter
