name: CBO2016
channels:
    - conda-forge
dependencies:
    - python=3.4
    - pip
    - anaconda-navigator
    - altair
    - cartopy
    - cmocean
    - console_shortcut
    - folium
    - iris
    - jupyter
    - matplotlib
    - mplleaflet
    - nb_conda_kernels
    - netcdf4
    - numpy
    - scipy
    - xarray
    - xlrd
